/*
  ____                                       
 |  _ \ ___ _ __ _   _ _ __  _ __   ___ _ __ 
 | |_) / _ \ '__| | | | '_ \| '_ \ / _ \ '__|
 |  _ <  __/ |  | |_| | | | | | | |  __/ |   
 |_| \_\___|_|   \__,_|_| |_|_| |_|\___|_|   
                                             
# A Sink Plugin that sends data to Rerun
# Generated by the command: plugin -t sink -d rerun_plugin -s rerun
# Hostname: Fram-IV.local
# Current working directory: /Users/p4010/Develop/MADS_plugins
# Creation date: 2025-09-08T16:35:50.334+0200
# NOTICE: MADS Version 2.0.0
*/

// Mandatory included headers
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>
#include <sink.hpp>

#include "moving_window_stats.hpp"
#include "skeleton.hpp"
#include <BS_thread_pool.hpp>
#include <array>
#include <chrono>
#include <datastore.hpp>
#include <deque>
#include <filesystem>
#include <future>
#include <iostream>
#include <memory>
#include <optional>
#include <rerun.hpp>
#include <unordered_map>
#include <unordered_set>
#include <vector>

// other includes as needed here

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "rerun"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;

// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
#include <deque>
#include <unordered_map>

class RerunnerPlugin : public Sink<json> {
private:
  std::vector<std::string> _keypaths;
  std::vector<std::string> _acf_keypaths;
  std::vector<std::string> _fft_keypaths;
  std::vector<std::string> _trace_keypaths;

  // The configured keypaths span every subscribed topic, but each message
  // carries a single topic. This caches, per topic actually seen, just the
  // keypaths that belong to it, so a message only ever probes its own keypaths
  // instead of all of them.
  struct TopicKeypaths {
    std::vector<std::string> scalars;
    std::vector<std::string> acf;
    std::vector<std::string> fft;
    std::vector<std::string> traces;
  };
  std::unordered_map<std::string, TopicKeypaths> _topic_cache;

  MovingWindowStats _stats;
  size_t _window_size = 1000; // Store 10x ACF width for better statistics
  filesystem::path _blueprint;

  std::chrono::steady_clock::time_point _start_time;
  std::shared_ptr<rerun::RecordingStream> _rec;

  unique_ptr<Skeleton> _skeleton;

  BS::thread_pool<BS::tp::none> _pool;
  vector<future<bool>> _futures;

  // Helper function to convert dot notation path to JSON value
  json::json_pointer dot_to_pointer(const std::string &dot_path) {
    std::string result;
    std::string token;
    bool in_brackets = false;
    if (dot_path[0] == '/') 
      return json::json_pointer(dot_path);

    for (char c : dot_path) {
      if (c == '[') {
        if (!token.empty()) {
          result += "/" + token;
          token.clear();
        }
        in_brackets = true;
      } else if (c == ']') {
        if (!token.empty()) {
          result += "/" + token;
          token.clear();
        }
        in_brackets = false;
      } else if (c == '.' && !in_brackets) {
        if (!token.empty()) {
          result += "/" + token;
          token.clear();
        }
      } else {
        token += c;
      }
    }

    if (!token.empty()) {
      result += "/" + token;
    }

    return json::json_pointer(result);
  }

  // Helper function to safely get a value from JSON using dot notation
  std::optional<double> get_numeric_value(const json &j,
                                          const std::string &dot_path) {
    json::json_pointer ptr = dot_to_pointer(dot_path);

    // Guard with contains() before dereferencing. On a *const* json,
    // operator[](json_pointer) resolves via get_unchecked(), whose object
    // branch performs an unchecked find()->second: for a missing key that
    // dereferences the map's end() iterator (the assert is compiled out under
    // NDEBUG) -> undefined behaviour / segfault, NOT a catchable exception.
    // This is the common case here: each message carries a single topic, yet
    // we probe every keypath, so keypaths belonging to other subscribed topics
    // are absent. contains() resolves the pointer safely and cheaply (no
    // exceptions on the miss path).
    if (!j.contains(ptr)) {
      return std::nullopt;
    }
    const json &value = j.at(ptr);
    if (value.is_number()) {
      return value.get<double>();
    }
    return std::nullopt;
  }

  // Return the keypaths belonging to `topic`, computing and caching the subset
  // on first sight. A keypath belongs to a topic when its JSON-pointer form is
  // prefixed by "/<topic>/" (the topic segments are the outer nesting levels of
  // `data`). Called single-threaded from load_data, before any pool task is
  // submitted, so the cache needs no locking.
  const TopicKeypaths &keypaths_for_topic(const std::string &topic) {
    auto it = _topic_cache.find(topic);
    if (it != _topic_cache.end()) {
      return it->second;
    }
    const std::string prefix = "/" + topic + "/";
    auto belongs = [&](const std::string &keypath) {
      const std::string ptr = dot_to_pointer(keypath).to_string();
      return ptr.size() > prefix.size() &&
             ptr.compare(0, prefix.size(), prefix) == 0;
    };
    TopicKeypaths tk;
    for (const auto &kp : _keypaths)
      if (belongs(kp)) tk.scalars.push_back(kp);
    for (const auto &kp : _acf_keypaths)
      if (belongs(kp)) tk.acf.push_back(kp);
    for (const auto &kp : _fft_keypaths)
      if (belongs(kp)) tk.fft.push_back(kp);
    for (const auto &kp : _trace_keypaths)
      if (belongs(kp)) tk.traces.push_back(kp);
    return _topic_cache.emplace(topic, std::move(tk)).first->second;
  }

public:
  RerunnerPlugin() {
    _start_time = std::chrono::steady_clock::now();
  }

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  return_type load_data(json const &input, string topic = "", vector<unsigned char> const *blob = nullptr) override {
    static double prev_time = 0;
    static double mean_dt = 0;
    static size_t n = 0;
    double dt = 0;
    bool logged = false;
    if (topic.empty()) {
      _error = "No topic specified in plugin load_data()";
      return return_type::error;
    }

    auto now = std::chrono::steady_clock::now();
    double time_seconds;
    // get the timecode from the input json if available, otherwise use elapsed
    // time
    if (!_params["time"].empty() && input.contains(_params["time"])) {
      time_seconds = input[_params["time"]].get<double>();
    } else {
      time_seconds = std::chrono::duration<double>(now - _start_time).count();
    }

    dt = time_seconds - prev_time;

    // embed the input json within nested objects, one per topic segment.
    // Topics may contain '/' (e.g. "test/my_source"); each segment becomes a
    // nesting level so that keypaths such as "/test/my_source/values/x"
    // resolve correctly via JSON pointer semantics (where '/' is the path
    // separator). A slash-free topic yields a single nesting level, matching
    // the previous behaviour.
    json data;
    {
      json *node = &data;
      string::size_type start = 0, slash;
      do {
        slash = topic.find('/', start);
        string segment = topic.substr(start, slash - start);
        if (slash == string::npos) {
          (*node)[segment] = input;
        } else {
          node = &((*node)[segment]);
          start = slash + 1;
        }
      } while (slash != string::npos);
    }

    // Only this topic's keypaths can resolve in `data`; skip all the others.
    const TopicKeypaths &tk = keypaths_for_topic(topic);

    // Extract values for each keypath and send to rerun
    if (_params["parallelize"].get<bool>()) {
      _futures.clear();
      _futures.reserve(tk.scalars.size());
      // Only numeric scalars carry statistics; remember which ones were present
      // in this message so the stats pass below runs solely over them, instead
      // of logging meaningless zeros for absent or non-numeric (flag/state)
      // keypaths.
      vector<string> numeric_keypaths;
      for (const auto &keypath : tk.scalars) {
        json::json_pointer ptr = dot_to_pointer(keypath);
        // Guard with contains() (see get_numeric_value): on a const json the
        // unchecked operator[] dereferences end() for a missing key -> UB.
        if (!data.contains(ptr)) {
          continue;
        }
        const json &value = data.at(ptr);
        if (value.is_number()) {
          double num = value.get<double>();
          _rec->log("data/" + keypath, rerun::Scalars(num));
          numeric_keypaths.push_back(keypath);
          // Capture by value: the task runs asynchronously on a pool thread,
          // long after this loop iteration (and its locals) has gone out of
          // scope.
          _futures.push_back(_pool.submit_task(
              [this, keypath, val = num] { return _stats.add(keypath, val); }));
          logged = true;
        } else if (value.is_boolean()) {
          // Booleans carry no statistics; log as a 0/1 step plot under flags/.
          _rec->log("flags/" + keypath,
                    rerun::Scalars(value.get<bool>() ? 1.0 : 0.0));
          logged = true;
        } else if (value.is_string()) {
          _rec->log("states/" + keypath,
                    rerun::TextLog(value.get<string>()));
          logged = true;
        }
      }
      for (const auto &f : _futures) {
        f.wait();
      }
      _futures.clear();
      for (const auto &keypath : numeric_keypaths) {
        _rec->log("stats/mean/" + keypath,
                  rerun::Scalars(_stats.mean(keypath)));
        _rec->log("stats/stdev/" + keypath,
                  rerun::Scalars(_stats.stdev(keypath)));
        _rec->log("stats/std_uncertainty/" + keypath,
                  rerun::Scalars(_stats.st_uncertainty(keypath)));
      }
    } else {
      for (const auto &keypath : tk.scalars) {
        json::json_pointer ptr = dot_to_pointer(keypath);
        // Guard with contains() (see get_numeric_value): on a const json the
        // unchecked operator[] dereferences end() for a missing key -> UB.
        // Most keypaths belong to other topics and are absent here.
        if (!data.contains(ptr)) {
          continue;
        }
        const json &value = data.at(ptr);
        if (value.is_number()) {
          double num = value.get<double>();
          _stats.add(keypath, num);
          _rec->log("data/" + keypath, rerun::Scalars(num));
          _rec->log("stats/mean/" + keypath,
                    rerun::Scalars(_stats.mean(keypath)));
          _rec->log("stats/stdev/" + keypath,
                    rerun::Scalars(_stats.stdev(keypath)));
          _rec->log("stats/std_uncertainty/" + keypath,
                    rerun::Scalars(_stats.st_uncertainty(keypath)));
          logged = true;
        } else if (value.is_boolean()) {
          // Booleans carry no statistics; log as a 0/1 step plot under flags/.
          _rec->log("flags/" + keypath,
                    rerun::Scalars(value.get<bool>() ? 1.0 : 0.0));
          logged = true;
        } else if (value.is_string()) {
          _rec->log("states/" + keypath,
                    rerun::TextLog(value.get<string>()));
          logged = true;
        } 
      }
    }

    // Traces
    for (const auto &keypath : tk.traces) {
      json::json_pointer ptr(dot_to_pointer(keypath));
      // Guard with contains() to avoid the non-const operator[] silently
      // creating the missing path in `data`.
      if (!data.contains(ptr)) {
        continue;
      }
      const json &point = data.at(ptr);
      if (point.is_array() && point.size() == 3) {
        _rec->log("trace/" + keypath, rerun::Points3D(rerun::Position3D(point)));
        logged = true;
      } else if (point.is_array() && point.size() == 2) {
        _rec->log("trace/" + keypath, rerun::Points2D(rerun::Position2D(point)));
        logged = true;
      } else {
        _error = "Trace keypath " + keypath + " does not point to a valid 2D or 3D point array";
        return return_type::error;
      }
    }

    // Process ACF keypaths
    for (const auto &keypath : tk.acf) {
      if (_stats.is_full(keypath)) {
        _rec->log("acf_plot/" + keypath,
                  rerun::BarChart::f64(_stats.acf(keypath)));
        logged = true;
      }
    }

    // Process FFT keypaths
    if (!tk.fft.empty()) {
      size_t len = _window_size / 2.0;
#ifdef WITH_ABSCISSA
      vector<double> abscissa;
      abscissa.reserve(len);
      for (size_t i = 1; i <= len; i++) {
        abscissa.push_back(i * 1 / mean_dt / 2.0 / (double)_window_size);
      }
      auto abscissa_data = rerun::TensorData(rerun::Collection{len}, abscissa);
#endif
      for (const auto &keypath : tk.fft) {
        if (_stats.is_full(keypath)) {
          _rec->log("fft_plot/" + keypath,
#ifdef WITH_ABSCISSA
                    rerun::BarChart::f64(_stats.fft(keypath))
                        .with_abscissa(abscissa_data));
#else
                    rerun::BarChart::f64(_stats.fft(keypath)));
#endif
          logged = true;
        }
      }
    }

    // Skeleton
    if (!_params["skeleton"].get<string>().empty()) {
      if (input["joints"].is_object())
        _skeleton->log(input["joints"]);
      else if (input[_params["skeleton"]].is_object())
        _skeleton->log(input[_params["skeleton"]]["joints"]);
      logged = true;
    }

    if (logged) {
      if (n > 0) {
        mean_dt = ((n - 1) * mean_dt + dt) / (double)n;
        _rec->log("stats/timestep", rerun::Scalars(dt));
        _rec->log("stats/mean_timestep", rerun::Scalars(mean_dt));
      }
      prev_time = time_seconds;
      n++;
      // Set the current time for this batch of data
      _rec->set_time_duration_secs("time", time_seconds);
      return return_type::retry;
    } else 
      return return_type::success;
  }

  void set_params(const json &params) override {
    // Call the parent class method to set the common parameters
    // (e.g. agent_id, etc.)
    Sink::set_params(params);

    // provide sensible defaults for the parameters
    _params["blueprint"] = "";
    _params["time"] = "timecode";
    _params["parallelize"] = true;
    _params["keypaths"] = json::array();       // empty array by default
    _params["acf_keypaths"] = json::array();   // empty array by default
    _params["fft_keypaths"] = json::array();   // empty array by default
    _params["trace_keypaths"] = json::array(); // empty array by default
    _params["window_size"] = 100;              // default ACF width
    _params["skeleton"] = string();            // empty string by default
    _params["3D_scale"] = 0.001;               // default scale for 3D data
    _params["show_axes"] = true;               // show skeleton axes by default
    _params["axes_length"] = 1000.0f;          // default axes length (mm)
    _params["nodes_radius"] = 1.0;             // default skeleton node radius
    _params["scene_file_path"] = string();     // empty string by default

    // then merge the defaults with the actually provided parameters
    _params.merge_patch(params);
    _window_size = _params.value("window_size", 200);
    _stats.reset(_window_size);

    // Keypaths are about to be reloaded; drop any cached per-topic grouping.
    _topic_cache.clear();

    _rec = std::make_shared<rerun::RecordingStream>("MADS " + _params.value("agent_name", "rerunner (generic)"));
    _rec->spawn().exit_on_failure();

    if (!_agent_id.empty()) {
      _rec->send_recording_name(_agent_id);
    }

    _blueprint = _params.value("blueprint", "");
    if (filesystem::exists(_blueprint)) {
      _rec->log_file_from_path(_blueprint);
    } else if (!_blueprint.empty()) {
      _blueprint = _params.value("blueprint", "") + " (not found)";
    }

    // Load the keypaths configuration. Duplicates are dropped: each keypath
    // owns one stats Signal, and the parallel path runs one add() task per
    // keypath, so two tasks sharing a key would race on the same object.
    _keypaths.clear();
    if (_params.contains("keypaths") && _params["keypaths"].is_array()) {
      std::unordered_set<std::string> seen;
      for (const auto &path : _params["keypaths"]) {
        if (path.is_string()) {
          auto keypath = path.get<std::string>();
          if (!seen.insert(keypath).second) {
            std::cerr << "[rerunner] WARNING: duplicate keypath \"" << keypath
                      << "\" ignored" << std::endl;
            continue;
          }
          _keypaths.push_back(std::move(keypath));
        }
      }
    }

    // Pre-register every keypath so the parallel add() tasks only ever look up
    // (never insert into) the stats map, keeping concurrent calls race-free.
    for (const auto &keypath : _keypaths) {
      _stats.register_key(keypath);
    }

    // Load ACF configuration
    _acf_keypaths.clear();
    if (_params.contains("acf_keypaths") &&
        _params["acf_keypaths"].is_array()) {
      for (const auto &path : _params["acf_keypaths"]) {
        if (path.is_string()) {
          _acf_keypaths.push_back(path.get<std::string>());
          // Initialize buffer for this keypath
          // _signal_buffers[path.get<std::string>()];
        }
      }
    }

    // Load FFT configuration
    _fft_keypaths.clear();
    if (_params.contains("fft_keypaths") &&
        _params["fft_keypaths"].is_array()) {
      for (const auto &path : _params["fft_keypaths"]) {
        if (path.is_string()) {
          _fft_keypaths.push_back(path.get<std::string>());
          // Initialize buffer for this keypath
          // _signal_buffers[path.get<std::string>()];
        }
      }
    }

    // Load trace configuration
    _trace_keypaths.clear();
    if (_params.contains("trace_keypaths") &&
        _params["trace_keypaths"].is_array()) {
      for (const auto &path : _params["trace_keypaths"]) {
        if (path.is_string()) {
          _trace_keypaths.push_back(path.get<std::string>());
          // Initialize buffer for this keypath
          // _signal_buffers[path.get<std::string>()];
        }
      }
    }

    // Skeleton
    if (!_params["skeleton"].get<string>().empty()) {
      _skeleton = make_unique<Skeleton>(_rec.get());

      _skeleton->set_radius(_params.value("nodes_radius", 1.0f));
      _skeleton->set_scale(_params.value("3D_scale", 0.001f));
      _skeleton->show_axes(_params.value("show_axes", true), _params.value("axes_length", 1000.0f));
      if (!_params.value("scene_file_path", "").empty()) {
        _skeleton->show_scene(
          _params["scene_file_path"].get<string>(),
          _params.value("scene_file_y_rot", 0.0f),
          _params.value("scene_file_offset", array<float, 3>{0.0, 0.0, 0.0}));
      }
    }
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override {
    // return a map of strings with additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent

    return {{"Rerun version", rerun::version_string()},
            {"Window size", std::to_string(_window_size)},
            {"ACF Keypaths",
             _acf_keypaths.empty() ? "None" : json(_acf_keypaths).dump()},
            {"FFT Keypaths",
             _fft_keypaths.empty() ? "None" : json(_fft_keypaths).dump()},
            {"Trace Keypaths",
             _trace_keypaths.empty() ? "None" : json(_trace_keypaths).dump()},
            {"Keypaths", _keypaths.empty() ? "None" : json(_keypaths).dump()},
            {"Skeleton field", _params["skeleton"].get<std::string>()},
            {"3D Scale", std::to_string(_params["3D_scale"].get<double>())},
            {"Scene file path", _params["scene_file_path"].get<string>().empty()
                                ? "None"
                                : _params["scene_file_path"].get<string>()},
            {"Scene rotation:", std::to_string(_params.value("scene_file_y_rot", 0.0))},
            {"Time column", _params["time"].get<string>().empty()
                                ? "timecode"
                                : _params["time"].get<std::string>()},
            {"Blueprint", (_blueprint.empty() ? "None" : _blueprint.string())},
            {"Parallelize", _params["parallelize"].get<bool>() ? to_string(_pool.get_thread_count()) + " threads" : "NO"}
          };
  };
};

/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
INSTALL_SINK_DRIVER(RerunnerPlugin, json)

/*
                  _
  _ __ ___   __ _(_)_ __
 | '_ ` _ \ / _` | | '_ \
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|

For testing purposes, when directly executing the plugin
*/
int main(int argc, char const *argv[]) {
  RerunnerPlugin plugin;
  json input, params;

  // Set example values to params
  params["test"] = "value";

  // Set the parameters
  plugin.set_params(params);

  // Process data
  plugin.load_data(input);

  return 0;
}
